### ISSUE TITLE
Conectar webservice municipal

### ISSUE THREAD

**Issue by avdata99** [OpenDataCordoba/funcionarios-cordoba#1]
Conectarse al webservice del municipio para detectar cambios en ese nivel de gobierno
https://gobiernoabierto.cordoba.gob.ar/api/funciones/

**Comment by nicolas471** [comment]
La idea seria reemplazar el scraper?

**Comment by avdata99** [comment]
Sería agregar uno nuevo @nicolas471. El que está es de la provincia y el que hay que agregar es de la municipalidad.

**Comment by avdata99** [comment]
Gracias Nico.
Tenés Twitter?

Echa un vistazo al Tweet de @FuncionariosCBA: https://twitter.com/FuncionariosCBA/status/1082634779164659712?s=09
