### ISSUE TITLE
Actualizar scraper Provincia de Córdoba

### ISSUE THREAD

**Issue by avdata99** [OpenDataCordoba/funcionarios-cordoba#15]
El sitio web cambio y es necesario actualizar [el scraper que estaba funcionando](https://github.com/OpenDataCordoba/funcionarios-cordoba/blob/master/funcionarios_prov_cba/funcionarios_prov_cba/spiders/funcionarios-cordoba.py) por uno nuevo que lea los datos desde el sitio https://www.cba.gov.ar/reparticiones/ (o encuentre fuentes mejores).

**Comment by nicolas471** [comment]
Yo lo puedo tomar!

**Comment by avdata99** [comment]
Gracias Nico!
Cambió la estética pero no la estructura al parecer
Si tenemos suerte es solo cuestión de tocar detalles

**Comment by j-e-d** [comment]
Hice un  PR en #16 sin consultar el estado del laburo de @nicolas471, disculpá la falta de gitiquette (?).

**Comment by lautarocastillo** [comment]
@avdata99 Podemos cerrar este issue? ya está en master
